version: 3

env:
  DOCKER_RUN:
    sh: echo "docker run --rm --user $UID -v $(pwd):/src -w /src ghcr.io/webassembly/wasi-sdk:wasi-sdk-27"

tasks:
  default:
    cmd: extism call --wasi --log-level=info build/qjs.wasm {{.CLI_ARGS}}
  preconditions:
    - command -v extism

  make:
    cmd: $DOCKER_RUN make -C build qjs_extism
    preconditions:
      - command -v docker

  cmake:
    cmd: $DOCKER_RUN cmake -B build -DCMAKE_TOOLCHAIN_FILE=/opt/wasi-sdk/share/cmake/wasi-sdk.cmake
    preconditions:
      - command -v docker

  build:
    cmds:
      - task: cmake
      - task: make
      - ls -lh build/qjs.wasm
    preconditions:
      - command -v docker

  clean:
    cmd: rm -rf build
