version: 3

env:
  DOCKER_RUN:
    sh: echo "docker run --rm --user $UID -v $(pwd):/src -w /src ghcr.io/webassembly/wasi-sdk:wasi-sdk-27"

tasks:
  default:
    cmd: extism call --wasi --log-level=info build/qjs.wasm {{.CLI_ARGS}}
  preconditions:
    - command -v extism

  make:
    cmds:
      - $DOCKER_RUN make -C build task_qjs
      - ls -lh build/qjs.wasm
    preconditions:
      - command -v docker

  cmake:
    cmd: $DOCKER_RUN cmake -B build -DQJS_ENABLE_CIVET=ON -DCMAKE_TOOLCHAIN_FILE=/opt/wasi-sdk/share/cmake/wasi-sdk.cmake
    preconditions:
      - command -v docker

  build:
    cmds:
      - task: cmake
      - task: make
    preconditions:
      - command -v docker

  clean:
    cmd: rm -rf build

  civet:
    cmd: |
      git submodule init
      git submodule update
      cd Civet
      git apply ../Civet.patch
      yarn install
      yarn build
      yarn terser dist/quickjs.mjs --compress --mangle --ecma 2015 --output dist/quickjs.min.mjs
      xxd -i Civet/dist/quickjs.min.mjs > civet.h
    preconditions:
      - command -v node
      - command -v yarn
      - command -v git
      - command -v xxd
